[BUG] Gradle plugin nativeCompile fails, when to start With Jobrunr (jobrunr-micronaut-feature 6.3.2) version when storage is MySql
- JobRunr unable to load applicationContext

Ref: Caused by: java.lang.NoSuchFieldError: No field 'applicationContext' found for type: org.jobrunr.micronaut.autoconfigure.JobRunrFactory